-- Runs as SYSDBA per Oracle container scripts mechanism
ALTER SESSION SET CONTAINER=FREEPDB1;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER ORDER_APP IDENTIFIED BY ORDER_APP';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN RAISE; END IF; -- already exists
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER USER ORDER_APP IDENTIFIED BY ORDER_APP ACCOUNT UNLOCK';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ORDER_APP';
EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ORDER_APP';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

ALTER SESSION SET CURRENT_SCHEMA=ORDER_APP;

BEGIN
EXECUTE IMMEDIATE 'CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE '
CREATE TABLE ORDERS (
                        ID NUMBER(19,0) PRIMARY KEY,
                        CUSTOMER_NAME VARCHAR2(200) NOT NULL,
                        ITEM VARCHAR2(200) NOT NULL,
                        QUANTITY NUMBER(10,0) NOT NULL,
                        STATUS VARCHAR2(40) NOT NULL,
                        CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/