CREATE SEQUENCE IF NOT EXISTS ORDERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ORDERS (
                                      ID BIGINT PRIMARY KEY,
                                      CUSTOMER_NAME VARCHAR(200) NOT NULL,
    ITEM VARCHAR(200) NOT NULL,
    QUANTITY INT NOT NULL,
    STATUS VARCHAR(40) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
                             );